package enums;

public enum SkillGroup {
	SG_ACTING, SG_ATHLETICS, SG_BIOTECH, SG_CLOSECOMBAT, SG_CONJURING, SG_CRACKING, SG_ELECTRONICS, SG_ENCHANTING, SG_FIREARMS, SG_INFLUENCE, SG_ENGINEERING, SG_OUTDOORS, SG_SORCERY, SG_STEALTH, SG_TASKING, KS_ACADEMIC, KS_INTERESTS, KS_PROFESSIONAL, KS_STREET, KS_LANGUAGE;
}
